### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/SpaceInvaders#2]
This project keeps being relevant because it is useful to teach (A)FRP, and because it is referenced in slides and papers.

There should be links to those, including videos if possible.

**Comment by vikramnr** [comment]
Can I help with these?

**Comment by ivanperez-keera** [comment]
Oh, that sounds great! Thank you so much :)

A reasonable starting point would be this: https://github.com/ivanperez-keera/Yampa/blob/develop/README.md

Including the top bar with the badges, installation, and papers.

This game was used in a paper called The Yampa Arcade, by Henrik Nilsson (details found here: http://www.cs.nott.ac.uk/~psznhn/papers.html#hw2003). He still uses it sometimes to explain FRP to new audiences. I'll ask him if there are slides that explain this.

It would be possible to add a screenshot too :)

**Comment by ivanperez-keera** [comment]
Forwarding a message I got earlier today from Henrik Nilsson:

> The slides from the 2003 talk are here:
> 
> http://www.cs.nott.ac.uk/~psznhn/Talks/HW2003-YampaArcade.pdf
> 
> There is a another talk that is more up to date but on FRP/Yampa
> more generally here:
> 
> http://www.cs.nott.ac.uk/~psznhn/Talks/7digital-July2016-IntroductionToFRPAndYampaThroughGamesAndMusic.pdf
> http://www.cs.nott.ac.uk/~psznhn/Talks/7digital-July2016-IntroductionToFRPAndYampaThroughGamesAndMusic-4up.pdf
> 
> It makes some comparisons with Cycle.js and XStreams which might
> be useful to some readers.
> 
> More generally, this series of lectures of FRP might also be relevant:
> 
> http://www.cs.nott.ac.uk/~psznhn/ITU-FRP2010/ITU-FRP2010.html
> 
> (This one does use Invaders as an example)

Many thanks for any help you can spare. From him and from me.
